# Generated by Django 3.2.16 on 2025-05-13 18:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_subscribed',
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(error_messages={'unique': 'Пользователь с таким именем уже существует.'}, max_length=150, unique=True, validators=[django.core.validators.RegexValidator(message='Юзернейм пользователя может содержать только буквы, а также следующие символы: ./@/+/-', regex='[\\w.@+-]+')], verbose_name='Юзернейм пользователя'),
        ),
    ]
