# Generated by Django 3.2.16 on 2025-05-20 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20250520_1539'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='avatar',
            new_name='image',
        ),
    ]
