# Generated by Django 3.2.16 on 2025-05-20 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_rename_avatar_recipe_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='username',
        ),
    ]
